import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>Hello I'm Main.</main>

      <footer>I'm Footer</footer>
    </div>
  );
};

export default Home;
